FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Expose React app port
EXPOSE 8080

# Start the React app
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8080"]
