FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Start the application in development mode (using ts-node)
RUN npm run build
CMD ["npm", "start"]

# Expose backend port
EXPOSE 5000

