name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger the action on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.59.194.63 << 'EOF'
            cd /home/ubuntu/heartlandshoppes-2.0 || exit
            git pull origin main || exit
            docker-compose down || exit
            docker-compose up --build -d || exit
          EOF
